title: Obsgynae
description: Obstetrics and gynacology resources to help provide the best in patient care
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: just-the-docs/just-the-docs
permalink: pretty

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/obsgynae-03-logowide.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Obsgynae on GitHub":
    - "https://github.com/obsgynae"

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Include links to parent and sibling pages when showing the automatic TOC. Default is false
nav_next_prev: true

# The default arrows can be changed to other characters or words
# nav_prev_text: "&larr;"
# nav_up_text:   "&uarr;"
# nav_next_text: "&rarr;"

# Caching navigation links
nav_cache: true # default, equivalent to nil

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer content appears at the bottom of every page's main content
footer_content: "Obsgynae Copyright &copy; Isaac Hanley.<br>Template Copyright &copy; 2017-2019 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Define Jekyll collections
collections:
  clinical-resources:
    permalink: "/:collection/:path:output_ext"
    output: true
  TheObsgynaePod:
    permalink: "/:collection/:path:output_ext"
    output: true

just_the_docs:
  collections:
    clinical-resources:
      name: Clinical resources
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    theObsgynaePod:
      name: TheObsgynaePod
      nav_exclude: false
      nav_fold: true
      search_exclude: false

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: #UA-2709176-10

plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
